#!/usr/bin/env node
const { args, input, colors, appendSlash } = require("./argparse.js")(`
book-zip [--in INPUT] [--output PATH] [-no-colors]

\`--in\` is the path to the epub contents, or './' by default
\`--output\` is the path to the output file, or './out.epub' by default

The \`zip\` command must be installed.
`);

const { spawnSync } = require("child_process");

const outputFile = args["output"] || "./out.epub";
const inputDir = (args["in"] && appendSlash(args["in"])) || "./";

console.log(`Creating epub '${colors.cyan}${outputFile}${colors.reset}' from '${colors.cyan}${inputDir}${colors.reset}'`);

const options = {
    stdio: "inherit",
    cwd: inputDir
};
const zipError = status => {
    console.error(`${colors.bold}${colors.red}ERROR${colors.reset}: 'zip' failed; exit code ${colors.red}${status}${colors.reset}`);
    process.exit(status);
};

var { status } = spawnSync("zip", ["-q", "-0", "-X", outputFile, "mimetype"], options);

if (status !== 0)
    zipError(status);

var { status } = spawnSync("zip", ["-q", "-9", "-r", outputFile, "toc.ncx", "META-INF", "EPUB"], options);

if (status !== 0)
    zipError(status);
