#!/usr/bin/env node
const { args, input, colors, appendSlash } = require("./argparse.js")(`
book-unzip INPUT [--output OUTPUT] [-no-colors]

\`INPUT\` is the path to the epub
\`--output\` is the path to the output directory, or './' by default

The \`unzip\` command must be installed.
`);

const { spawnSync } = require("child_process");

const outputDir = (args["output"] && appendSlash(args["output"])) || "./";
const inputFile = input[0] || "./out.epub";

console.log(`Extracting epub '${colors.cyan}${inputFile}${colors.reset}' to '${colors.cyan}${outputDir}${colors.reset}'`);

const { status } = spawnSync("unzip", ["-q", "-d", outputDir, inputFile], {
    stdio: "inherit"
});

if (status !== 0) {
    console.error(`${colors.bold}${colors.red}ERROR${colors.reset}: 'zip' failed; exit code ${colors.red}${status}${colors.reset}`);
    process.exit(status);
}
