#!/usr/bin/env node
const { args, input, colors } = require("./argparse.js")(`
book-meta INPUT [-no-colors]

\`INPUT\` is the path to the epub manifest file or './EPUB/package.opf' by default
`);

const fs = require("fs");
const readline = require("readline");
const inputFile = input[0] || "./EPUB/package.opf";

let data = fs.readFileSync(inputFile, "utf8");
const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

console.log(`Editing '${colors.cyan}${inputFile}${colors.reset}'\n`);

rl.on("close", () => {
    fs.writeFileSync(inputFile, data, "utf8");
});

function getInput(questions) {
    const question = questions.shift();
    const [property, value] = question[1](question[0]);
    rl.question(`${property}${(value && " [" + value + "]") || ""}: `, input => {
        input = input.trim();
        if (input && value) {
            // New value, element already exists -> replace
            data = data.replace(question[0], question[2](input));
        } else if (input && !value) {
            // New value, element does not exist -> insert
            data = data.replace(/(<metadata.*?>)(\s*)/, "$1$2" + question[2](input) + "$2");
        } // No new value -> do nothing

        questions.length === 0 ? rl.close() : getInput(questions);
    });
}

getInput([
    [
        /<dc:title>(.*?)<\/dc:title>/,
        (regex) => {
            const match = regex.exec(data);
            return ["Book title", match && match[1]];
        },
        v => `<dc:title>${v}</dc:title>`
    ],
    [
        /<dc:creator.*?>(.*?)<\/dc:creator>(\s*)?(<meta.*?property="role".*?<\/meta>)?/,
        (regex) => {
            const match = regex.exec(data);
            return ["Author", match && match[1]];
        },
        v => `<dc:creator id="creator">${v}</dc:creator>$2<meta refines="#creator" property="role" scheme="marc:relators">aut</meta>`
    ],
    [
        /<dc:language>(.*?)<\/dc:language>/,
        (regex) => {
            const match = regex.exec(data);
            return ["Language (short code)", match && match[1]];
        },
        v => `<dc:language>${v}</dc:language>`
    ],
    [
        /<dc:date>(.*?)<\/dc:date>/,
        (regex) => {
            const match = regex.exec(data);
            return ["Date of the EPUB creation", match && match[1]];
        },
        v => `<dc:date>${v}</dc:date>`
    ],
    [
        /<meta property="dcterms:created">(.*?)<\/meta>/,
        (regex) => {
            const match = regex.exec(data);
            return ["Creation date", match && match[1]];
        },
        v => `<meta property="dcterms:created">${v}</meta>`
    ],
    [
        /<dc:subject>(.*?)<\/dc:subject>/,
        (regex) => {
            const match = regex.exec(data);
            return ["Tags", match && match[1]];
        },
        v => `<dc:subject>${v}</dc:subject>`
    ],
    [
        /<meta property="dcterms:source">(.*?)<\/meta>/,
        (regex) => {
            const match = regex.exec(data);
            return ["Source", match && match[1]];
        },
        v => `<meta property="dcterms:source">${v}</meta>`
    ],
    [
        /<dc:description>&lt;div&gt;(.*?)&lt;\/div&gt;<\/dc:description>/,
        (regex) => {
            const match = regex.exec(data);
            return ["Description", "\n" + (match && unescapeHTML(match[1])) + "\n"];
        },
        v => `<dc:description>&lt;div&gt;${escapeHTML(v)}&lt;/div&gt;</dc:description>`
    ],
]);

function escapeHTML(input) {
    return input
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;");
}

function unescapeHTML(input) {
    return input
        .replace(/&lt;/g, "<")
        .replace(/&gt;/g, ">")
        .replace(/&quot;/g, '"');
}
